### ISSUE TITLE
[Bug]: MultiCombobox dismisses dropdown after every selection

### ISSUE THREAD

**Issue by partlysean44** [project44/manifest#446] opened 2023-08-03 22:04 UTC
### Description

The MultiCombobox's dropdown dismisses every time you make a selection. Since this component is intended to choose multiple items, it should stay visible until the user de-focuses from the input.

![2023-08-03 17 02 13](https://github.com/project44/manifest/assets/139248410/bad66636-ec9e-4d86-aa11-5bdd493448d7)

### Link to reproduction

https://project44.github.io/manifest/inputs/mult-combobox

### Steps to reproduce

You can experience this here: https://project44.github.io/manifest/inputs/mult-combobox

### Code of Conduct

- [X] I agree to the [Code of Conduct](https://github.com/project44/manifest/blob/main/.github/CODE_OF_CONDUCT.md).
- [X] I have reviewed the [current issues](https://github.com/project44/manifest/issues) for duplicate tickets.

**Comment by vivek-p44** [comment] 2023-10-17 10:08
@aamir-p44 @smartinelli-p44  I have tried reproducing this as per details mentioned above in the ticket, but i am not able to reproduce this. I am attaching a screen recording for reference.


https://github.com/project44/manifest/assets/147403156/ae59795e-d7b2-4360-860c-2316f51c4364

**Comment by vivek-p44** [comment] 2023-10-31 08:35
This is already fixed by @kaushikSarma in this PR, so i think we can close this one.
@aamir-p44  @smartinelli-p44 Can we close this one ?

**Closed** 2023-10-31 13:21 UTC
Labels: bug
